errand-config:
  delete-space:
    pre-delete-state: default
  push-apps:
    post-deploy-state: default
  smoke-tests:
    post-deploy-state: default
network-properties:
  network:
    name: PAS-Infrastructure
  other_availability_zones:
  - name: pas-az1
  service_network:
    name: PAS-Services
  singleton_availability_zone:
    name: pas-az1
product-name: p-healthwatch
product-properties:
  .healthwatch-forwarder.boshhealth_instance_count:
    value: 1
  .healthwatch-forwarder.boshtasks_instance_count:
    value: 2
  .healthwatch-forwarder.canary_instance_count:
    value: 2
  .healthwatch-forwarder.cli_instance_count:
    value: 2
  .healthwatch-forwarder.foundation_name:
    value: haas-222
  .healthwatch-forwarder.health_check_az:
    value: pas-az1
  .healthwatch-forwarder.health_check_vm_type:
    value: micro
  .healthwatch-forwarder.ingestor_instance_count:
    value: 4
  .healthwatch-forwarder.opsman_instance_count:
    value: 2
  .healthwatch-forwarder.publish_to_eva:
    value: true
  .healthwatch-forwarder.worker_instance_count:
    value: 4
  .properties.boshtasks:
    selected_option: disable
    value: disable
  .properties.indicators_selector:
    value: "No"
  .properties.opsman:
    value: enable
  .properties.opsman.enable.url:
    value: https://opsmgr-01.haas-222.pez.pivotal.io/
  .properties.syslog_selector:
    value: "No"
resource-config:
  healthwatch-forwarder:
    instance_type:
      id: automatic
    instances: automatic
    persistent_disk:
      size_mb: automatic
  mysql:
    instance_type:
      id: automatic
    instances: automatic
    persistent_disk:
      size_mb: automatic
  redis:
    instance_type:
      id: automatic
    instances: automatic
    persistent_disk:
      size_mb: automatic