---
product-name: pivotal-mysql
product-properties:
  .properties.allow_lower_case_table_names_via_config_param:
    value: false
  .properties.audit_logging_enabled:
    value: false
  .properties.backups_selector:
    selected_option: scp
    value: SCP Backups
  .properties.backups_selector.scp.cron_schedule:
    value: 0 */8 * * *
  .properties.backups_selector.scp.destination:
    value: /
  .properties.backups_selector.scp.enable_email_alerts:
    value: false
  .properties.backups_selector.scp.key:
    value:
      secret: asdf
  .properties.backups_selector.scp.port:
    value: 22
  .properties.backups_selector.scp.server:
    value: asdf
  .properties.backups_selector.scp.user:
    value: asdf
  .properties.canary_instances:
    value: 0
  .properties.deprecated_bindings_string:
    value: X
  .properties.enable_lower_case_table_names:
    value: false
  .properties.enable_read_only_admin:
    value: false
  .properties.enable_secure_binding_credentials:
    value: false
  .properties.enable_tls_selector:
    selected_option: disabled
    value: disabled
  .properties.global_recipient_email:
    value: tthomas@pivotal.io
  .properties.global_service_instance_limit:
    value: 200
  .properties.local_infile:
    value: false
  .properties.mysql_metrics_frequency:
    value: 30
  .properties.plan1_selector:
    selected_option: single_node
    value: single_node
  .properties.plan1_selector.single_node.access_dropdown:
    value: enable
  .properties.plan1_selector.single_node.az_multi_select:
    value:
    - pas-az1
    - pas-az2
    - pas-az3
  .properties.plan1_selector.single_node.description:
    value: This plan provides a small dedicated MySQL instance.
  .properties.plan1_selector.single_node.name:
    value: db-small
  .properties.plan1_selector.single_node.paid_plan:
    value: false
  .properties.plan2_selector:
    selected_option: inactive
    value: Inactive
  .properties.plan3_selector:
    selected_option: inactive
    value: Inactive
  .properties.plan4_selector:
    selected_option: inactive
    value: Inactive
  .properties.plan5_selector:
    selected_option: inactive
    value: Inactive
  .properties.plan6_selector:
    selected_option: inactive
    value: Inactive
  .properties.plan7_selector:
    selected_option: inactive
    value: Inactive
  .properties.plan8_selector:
    selected_option: inactive
    value: Inactive
  .properties.plan9_selector:
    selected_option: inactive
    value: Inactive
  .properties.request_timeout:
    value: 120
  .properties.simultaneous_upgrades:
    value: 1
  .properties.syslog_migration_selector:
    selected_option: disabled
    value: disabled
  .properties.userstat:
    value: false
  .properties.wait_timeout:
    value: 28800
network-properties:
  network:
    name: PAS-Deployment
  other_availability_zones:
  - name: pas-az1
  - name: pas-az2
  - name: pas-az3
  service_network:
    name: PAS-Services
  singleton_availability_zone:
    name: pas-az1
resource-config:
  dedicated-mysql-broker:
    instances: automatic
    instance_type:
      id: automatic
    max_in_flight: 1
errand-config:
  delete-all-service-instances-and-deregister-broker:
    pre-delete-state: true
  register-broker:
    post-deploy-state: true
  smoke-tests:
    post-deploy-state: true
  upgrade-all-service-instances:
    post-deploy-state: true
  validate-before-upgrade-instances:
    post-deploy-state: true